version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=my_social_web_docker
    ports:
      - "3308:3306"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"  # Cổng cho RabbitMQ
      - "15672:15672" # Cổng cho giao diện quản lý (management UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Thay đổi tên người dùng
      RABBITMQ_DEFAULT_PASS: guest  # Thay đổi mật khẩu
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE  # Hoặc OUTSIDE tùy vào nhu cầu của bạn
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  rabbitmq_data:
  kafka_data:
